import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUserTable1762477338663 implements MigrationInterface {
    name = 'CreateUserTable1762477338663'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(15) NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_status\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`network\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contract\` DROP FOREIGN KEY \`FK_6a885266d22e35f6b615d350bfb\``);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`symbol\` \`symbol\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`decimals\` \`decimals\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`network_id\` \`network_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`asset\` DROP FOREIGN KEY \`FK_4236ebf54cc778a0a745ba71517\``);
        await queryRunner.query(`ALTER TABLE \`asset\` DROP FOREIGN KEY \`FK_e4f965669f80e69a2031122de1c\``);
        await queryRunner.query(`ALTER TABLE \`asset\` CHANGE \`image\` \`image\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`asset\` CHANGE \`network_id\` \`network_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`asset\` CHANGE \`contract_id\` \`contract_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` DROP FOREIGN KEY \`FK_eac9bd34c0aed14e58f81f9ed68\``);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` DROP FOREIGN KEY \`FK_b20cffc4251db055f8317fe736a\``);
        await queryRunner.query(`DROP INDEX \`IDX_93a471f06b7c85414b94913262\` ON \`swap_pair\``);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`from_asset_id\` \`from_asset_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`to_asset_id\` \`to_asset_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`from_min_amount\` \`from_min_amount\` decimal(38,18) NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`from_max_amount\` \`from_max_amount\` decimal(38,18) NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_4877e54f9f739184dcb46d5352f\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_42811d745c26cfcdd003a36b9d6\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_e4b9555a4dc8a576647d32b38d7\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_c6bde344588be542ee2ddb81ca5\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`from_asset_id\` \`from_asset_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`to_asset_id\` \`to_asset_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`to_txhash\` \`to_txhash\` char(66) NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`status_id\` \`status_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`from_network_id\` \`from_network_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pool\` DROP FOREIGN KEY \`FK_338531367ed63e3eb8e1939980f\``);
        await queryRunner.query(`ALTER TABLE \`pool\` DROP FOREIGN KEY \`FK_479321eabdd500587fddd0ee88b\``);
        await queryRunner.query(`ALTER TABLE \`pool\` DROP FOREIGN KEY \`FK_199879a88c514fef85739b977bc\``);
        await queryRunner.query(`DROP INDEX \`IDX_34236b4aacda379cf5b8a38770\` ON \`pool\``);
        await queryRunner.query(`ALTER TABLE \`pool\` CHANGE \`token0_id\` \`token0_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pool\` CHANGE \`token1_id\` \`token1_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pool\` CHANGE \`network_id\` \`network_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction_type\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_acab4558de36fee3a6741400c0e\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_2380060e43d683d3e3622c132fd\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_f39edfe319f8858f383551c2f2c\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_13f79cbec10617a36fd0c659584\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`type_id\` \`type_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`pool_id\` \`pool_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`token0_id\` \`token0_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`token1_id\` \`token1_id\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_93a471f06b7c85414b94913262\` ON \`swap_pair\` (\`from_asset_id\`, \`to_asset_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_34236b4aacda379cf5b8a38770\` ON \`pool\` (\`token0_id\`, \`token1_id\`)`);
        await queryRunner.query(`ALTER TABLE \`contract\` ADD CONSTRAINT \`FK_6a885266d22e35f6b615d350bfb\` FOREIGN KEY (\`network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`asset\` ADD CONSTRAINT \`FK_4236ebf54cc778a0a745ba71517\` FOREIGN KEY (\`network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`asset\` ADD CONSTRAINT \`FK_e4f965669f80e69a2031122de1c\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contract\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` ADD CONSTRAINT \`FK_eac9bd34c0aed14e58f81f9ed68\` FOREIGN KEY (\`from_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` ADD CONSTRAINT \`FK_b20cffc4251db055f8317fe736a\` FOREIGN KEY (\`to_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_4877e54f9f739184dcb46d5352f\` FOREIGN KEY (\`from_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_42811d745c26cfcdd003a36b9d6\` FOREIGN KEY (\`to_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_c6bde344588be542ee2ddb81ca5\` FOREIGN KEY (\`from_network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_e4b9555a4dc8a576647d32b38d7\` FOREIGN KEY (\`status_id\`) REFERENCES \`swap_status\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool\` ADD CONSTRAINT \`FK_199879a88c514fef85739b977bc\` FOREIGN KEY (\`network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool\` ADD CONSTRAINT \`FK_338531367ed63e3eb8e1939980f\` FOREIGN KEY (\`token0_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool\` ADD CONSTRAINT \`FK_479321eabdd500587fddd0ee88b\` FOREIGN KEY (\`token1_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_acab4558de36fee3a6741400c0e\` FOREIGN KEY (\`type_id\`) REFERENCES \`pool_transaction_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_2380060e43d683d3e3622c132fd\` FOREIGN KEY (\`pool_id\`) REFERENCES \`pool\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_f39edfe319f8858f383551c2f2c\` FOREIGN KEY (\`token0_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_13f79cbec10617a36fd0c659584\` FOREIGN KEY (\`token1_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_13f79cbec10617a36fd0c659584\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_f39edfe319f8858f383551c2f2c\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_2380060e43d683d3e3622c132fd\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` DROP FOREIGN KEY \`FK_acab4558de36fee3a6741400c0e\``);
        await queryRunner.query(`ALTER TABLE \`pool\` DROP FOREIGN KEY \`FK_479321eabdd500587fddd0ee88b\``);
        await queryRunner.query(`ALTER TABLE \`pool\` DROP FOREIGN KEY \`FK_338531367ed63e3eb8e1939980f\``);
        await queryRunner.query(`ALTER TABLE \`pool\` DROP FOREIGN KEY \`FK_199879a88c514fef85739b977bc\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_e4b9555a4dc8a576647d32b38d7\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_c6bde344588be542ee2ddb81ca5\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_42811d745c26cfcdd003a36b9d6\``);
        await queryRunner.query(`ALTER TABLE \`swap_history\` DROP FOREIGN KEY \`FK_4877e54f9f739184dcb46d5352f\``);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` DROP FOREIGN KEY \`FK_b20cffc4251db055f8317fe736a\``);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` DROP FOREIGN KEY \`FK_eac9bd34c0aed14e58f81f9ed68\``);
        await queryRunner.query(`ALTER TABLE \`asset\` DROP FOREIGN KEY \`FK_e4f965669f80e69a2031122de1c\``);
        await queryRunner.query(`ALTER TABLE \`asset\` DROP FOREIGN KEY \`FK_4236ebf54cc778a0a745ba71517\``);
        await queryRunner.query(`ALTER TABLE \`contract\` DROP FOREIGN KEY \`FK_6a885266d22e35f6b615d350bfb\``);
        await queryRunner.query(`DROP INDEX \`IDX_34236b4aacda379cf5b8a38770\` ON \`pool\``);
        await queryRunner.query(`DROP INDEX \`IDX_93a471f06b7c85414b94913262\` ON \`swap_pair\``);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`token1_id\` \`token1_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`token0_id\` \`token0_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`pool_id\` \`pool_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` CHANGE \`type_id\` \`type_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_13f79cbec10617a36fd0c659584\` FOREIGN KEY (\`token1_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_f39edfe319f8858f383551c2f2c\` FOREIGN KEY (\`token0_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_2380060e43d683d3e3622c132fd\` FOREIGN KEY (\`pool_id\`) REFERENCES \`pool\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction\` ADD CONSTRAINT \`FK_acab4558de36fee3a6741400c0e\` FOREIGN KEY (\`type_id\`) REFERENCES \`pool_transaction_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool_transaction_type\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pool\` CHANGE \`network_id\` \`network_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pool\` CHANGE \`token1_id\` \`token1_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pool\` CHANGE \`token0_id\` \`token0_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_34236b4aacda379cf5b8a38770\` ON \`pool\` (\`token0_id\`, \`token1_id\`)`);
        await queryRunner.query(`ALTER TABLE \`pool\` ADD CONSTRAINT \`FK_199879a88c514fef85739b977bc\` FOREIGN KEY (\`network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool\` ADD CONSTRAINT \`FK_479321eabdd500587fddd0ee88b\` FOREIGN KEY (\`token1_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pool\` ADD CONSTRAINT \`FK_338531367ed63e3eb8e1939980f\` FOREIGN KEY (\`token0_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`from_network_id\` \`from_network_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`status_id\` \`status_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`to_txhash\` \`to_txhash\` char(66) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`to_asset_id\` \`to_asset_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` CHANGE \`from_asset_id\` \`from_asset_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_c6bde344588be542ee2ddb81ca5\` FOREIGN KEY (\`from_network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_e4b9555a4dc8a576647d32b38d7\` FOREIGN KEY (\`status_id\`) REFERENCES \`swap_status\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_42811d745c26cfcdd003a36b9d6\` FOREIGN KEY (\`to_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_history\` ADD CONSTRAINT \`FK_4877e54f9f739184dcb46d5352f\` FOREIGN KEY (\`from_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`from_max_amount\` \`from_max_amount\` decimal(38,18) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`from_min_amount\` \`from_min_amount\` decimal(38,18) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`to_asset_id\` \`to_asset_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` CHANGE \`from_asset_id\` \`from_asset_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_93a471f06b7c85414b94913262\` ON \`swap_pair\` (\`from_asset_id\`, \`to_asset_id\`)`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` ADD CONSTRAINT \`FK_b20cffc4251db055f8317fe736a\` FOREIGN KEY (\`to_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`swap_pair\` ADD CONSTRAINT \`FK_eac9bd34c0aed14e58f81f9ed68\` FOREIGN KEY (\`from_asset_id\`) REFERENCES \`asset\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`asset\` CHANGE \`contract_id\` \`contract_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`asset\` CHANGE \`network_id\` \`network_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`asset\` CHANGE \`image\` \`image\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`asset\` ADD CONSTRAINT \`FK_e4f965669f80e69a2031122de1c\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contract\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`asset\` ADD CONSTRAINT \`FK_4236ebf54cc778a0a745ba71517\` FOREIGN KEY (\`network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`network_id\` \`network_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`decimals\` \`decimals\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contract\` CHANGE \`symbol\` \`symbol\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contract\` ADD CONSTRAINT \`FK_6a885266d22e35f6b615d350bfb\` FOREIGN KEY (\`network_id\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`network\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`swap_status\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(15) NULL DEFAULT 'NULL'`);
    }

}
