export enum LogTag {
  DATABASE = 'DATABASE',
  REQUEST_START = 'REQUEST_START',
  REQUEST_END = 'REQUEST_END',
  REQUEST_ERROR = 'REQUEST_ERROR',
  JOB_START = 'JOB_START',
  JOB_END = 'JOB_END',
  JOB_ERROR = 'JOB_ERROR',
  SOCKET_ERROR = 'SOCKET_ERROR',
}
