export enum ConfigKey {
  'VERIFY_EMAIL_CODE_EXPIRES_IN_MINUTES' = 'VERIFY_EMAIL_CODE_EXPIRES_IN_MINUTES',
  'RESET_PASSWORD_CODE_EXPIRES_IN_MINUTES' = 'RESET_PASSWORD_CODE_EXPIRES_IN_MINUTES',
  'SELL_TICKET_FEE_RATE' = 'SELL_TICKET_FEE_RATE',
}
